language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maxim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maxim/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-eu-central-1-908841334002"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"